/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fbf8fa',
        'surface-dim': '#dcd9db',
        'surface-bright': '#fbf8fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f4',
        'surface-container': '#f0edef',
        'surface-container-high': '#eae7e9',
        'surface-container-highest': '#e4e2e3',
        'on-surface': '#1b1b1d',
        'on-surface-variant': '#45474c',
        'inverse-surface': '#303032',
        'inverse-on-surface': '#f3f0f2',
        'outline': '#75777d',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#545f73',
        'primary': '#091426',
        'on-primary': '#ffffff',
        'primary-container': '#1e293b',
        'on-primary-container': '#8590a6',
        'inverse-primary': '#bcc7de',
        'secondary': '#006a61',
        'on-secondary': '#ffffff',
        'secondary-container': '#86f2e4',
        'on-secondary-container': '#006f66',
        'tertiary': '#1e1200',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#35260c',
        'on-tertiary-container': '#a38c6a',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e3fb',
        'primary-fixed-dim': '#bcc7de',
        'on-primary-fixed': '#111c2d',
        'on-primary-fixed-variant': '#3c475a',
        'secondary-fixed': '#89f5e7',
        'secondary-fixed-dim': '#6bd8cb',
        'on-secondary-fixed': '#00201d',
        'on-secondary-fixed-variant': '#005049',
        'tertiary-fixed': '#fadfb8',
        'tertiary-fixed-dim': '#ddc39d',
        'on-tertiary-fixed': '#271902',
        'on-tertiary-fixed-variant': '#564427',
        'background': '#fbf8fa',
        'on-background': '#1b1b1d',
        'surface-variant': '#e4e2e3',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
      spacing: {
        'sidebar-width': '260px',
        'container-max-width': '1440px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      }
    },
  },
  plugins: [],
}
